name: flutter_user_sdk
description: UserComSDK that simplify sending events and receiving campaign notifications
version: 0.0.2
homepage: https://github.com/UserEngage/Flutter-SDK

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit_generator: ^4.0.1
  firebase_messaging: ^11.2.11
  firebase_core: ^1.15.0
  retrofit: ^3.0.1+1
  device_info_plus: ^3.2.2
  dio: ^4.0.6
  json_serializable: ^6.1.6
  advertising_id: ^2.3.0
  connectivity_plus: ^2.3.0
  hive: ^2.1.0
  path_provider: ^2.0.9
  firebase_analytics: ^9.1.6
  flutter_custom_tabs: ^1.0.4
  another_flushbar: ^1.10.29
  awesome_notifications: 0.7.0-beta.6
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:

