name: flutter_user_sdk
description: UserComSDK that simplify sending events and receiving campaign notifications
version: 1.0.1
homepage: https://github.com/UserEngage/Flutter-SDK

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: " >=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit_generator: ^9.1.4
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  retrofit: ^4.4.1
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  json_serializable: ^6.8.0
  advertising_id: ^2.7.1
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  another_flushbar: ^1.12.30
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.3
  build_runner: any

